ckpt: './checkpoints/base.pth'
conf_ckpt: './checkpoints/conf.pth'

data:
  data: ncaa
  train_path:
  test_path:  './data/ncaa/processed/test_data_256.pth'

train:
  name: test
  batch_size: 1
  num_epochs: 2000
  lr: 1.0e-4
  weight_decay: 0.0
  grad_norm: 1.0
  lr_schedule: False
  lr_decay: 0.999
  ema: 0.999
  print_interval: 1
  save_interval: 1
  loss_type: vf

sample:
  batch_size: 1
  n_samples: 8
  num_timesteps: 10

model:
  name: af3
  s_in: 19
  z_in: 6
  s_dim: 128
  z_dim: 64
  n_pf_layers: 16
  n_atom_layers: 4
  embed_mask: True
  embed_aa: False
  reset_backbone: True
  random_augment: True
  add_noise: True